/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp -m -p dbusmenu_interface /home/septemberhx/Workspace/git/dde-top-panel/appmenu/com.canonical.dbusmenu.xml
 *
 * qdbusxml2cpp is Copyright (C) 2017 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#include "dbusmenu_interface.h"

/*
 * Implementation of interface class ComCanonicalDbusmenuInterface
 */

ComCanonicalDbusmenuInterface::ComCanonicalDbusmenuInterface(const QString &service, const QString &path, const QDBusConnection &connection, QObject *parent)
    : QDBusAbstractInterface(service, path, staticInterfaceName(), connection, parent)
{
}

ComCanonicalDbusmenuInterface::~ComCanonicalDbusmenuInterface()
{
}


#include "dbusmenu_interface.moc"
